# Generated by Django 5.2.4 on 2026-04-24 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='reviews',
            index=models.Index(fields=['user', 'created_at'], name='Отзывы_user_id_4f88a1_idx'),
        ),
        migrations.AddIndex(
            model_name='reviews',
            index=models.Index(fields=['stars'], name='Отзывы_stars_6b70b2_idx'),
        ),
    ]
