# Generated by Django 5.2.4 on 2026-04-24 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='availabledate',
            index=models.Index(fields=['date'], name='orders_avai_date_3192ae_idx'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.availabledate', verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='orders.availabledate', verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.availabletime', verbose_name='Время'),
        ),
        migrations.AddIndex(
            model_name='availabletime',
            index=models.Index(fields=['date', 'freely'], name='orders_avai_date_id_706566_idx'),
        ),
        migrations.AddIndex(
            model_name='availabletime',
            index=models.Index(fields=['time'], name='orders_avai_time_0c36b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='availabletime',
            unique_together={('date', 'time')},
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date', 'time'], name='orders_appo_date_id_88ce03_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user', 'created_at'], name='orders_appo_user_id_af6643_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['phone'], name='orders_appo_phone_26ca82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'time')},
        ),
    ]
